### ISSUE TITLE
 www-apps/gitlab-ce-9.1.4 upgrade failed

### ISSUE THREAD

**Issue by Kami-no** [fritteli/gentoo-overlay#47]
```
[4/4] Building fresh packages...
Done in 22.67s.
 * Cleaning old precompiled assets ...
   /usr/bin/ruby /usr/bin/bundle exec rake gitlab:assets:clean RAILS_ENV=production NODE_ENV=production
I, [2017-05-27T21:04:40.213480 #1872]  INFO -- : Removed application-95970f1eedaa338f70cfe32c114efe83439793bf96581dd001b6d96ce2e04c50.css
 * Cleaning cache ...
   /usr/bin/ruby /usr/bin/bundle exec rake cache:clear RAILS_ENV=production NODE_ENV=production
 * Precompiling assests ...
   /usr/bin/ruby /usr/bin/bundle exec rake gitlab:assets:compile RAILS_ENV=production NODE_ENV=production
warning fsevents@1.0.17: The platform "linux" is incompatible with this module.
/opt/gitlab/node_modules/.bin/webpack --config /opt/gitlab/config/webpack.config.js --bail
Hash: 176d11821dff38b63dec
Version: webpack 2.3.3
Time: 64735ms
[3V7F] ./protected_branches/protected_branches_bundle.js 201 bytes {19} [built]
[3Yvy] ./groups_list.js 591 bytes {0} [built]
[45VA] ./network/network_bundle.js 625 bytes {22} [built]
[80jL] ./commit/pipelines/pipelines_bundle.js 922 bytes {4} [built]
[8z1L] ./commons/index.js 62 bytes {1} [built]
[CtDz] ./blob_edit/blob_bundle.js 1.09 kB {13} [built]
   [1] multi d3 28 bytes {26} [built]
   [2] multi vendor/u2f 28 bytes {25} [built]
[RUZQ] ./profile/profile_bundle.js 43 bytes {23} [built]
[iVFC] ./blob/notebook_viewer.js 104 bytes {17} [built]
[jsyL] ./vue_pipelines_index/index.js 455 bytes {3} [built]
[nYj/] ./blob/stl_viewer.js 569 bytes {21} [built]
[pqyH] ./blob/pdf_viewer.js 89 bytes {16} [built]
[wYwm] ./issue_show/index.js 556 bytes {11} [built]
   [3] multi vue ./vue_shared/common_vue.js 40 bytes {14} [built]
    + 637 hidden modules

ERROR in main.b66fa35e661cc9a3b9bb.bundle.js from UglifyJs
Unexpected token: name (CreateBranchDropdown) [./blob/create_branch_dropdown.js:1,6][main.b66fa35e661cc9a3b9bb.bundle.js:588,6]

ERROR in common.3606a55edd25cb454e34.bundle.js from UglifyJs
Unexpected token operator «=», expected punc «,» [./commons/polyfills/element.js:2,29][common.3606a55edd25cb454e34.bundle.js:7980,100]

ERROR in sketch_viewer.0abacbb479e7c8d0697e.bundle.js from UglifyJs
Unexpected token: punc ()) [./blob/sketch_viewer.js:4,46][sketch_viewer.0abacbb479e7c8d0697e.bundle.js:455,47]

ERROR in vue_pipelines.50c2c7d0d6f03abe40b6.bundle.js from UglifyJs
Unexpected token: name (PipelinesService) [./vue_pipelines_index/services/pipelines_service.js:7,21][vue_pipelines.50c2c7d0d6f03abe40b6.bundle.js:23,6]

ERROR in commit_pipelines.63e6341eb08f12dc6811.bundle.js from UglifyJs
Unexpected token: name (PipelinesService) [./vue_pipelines_index/services/pipelines_service.js:7,21][commit_pipelines.63e6341eb08f12dc6811.bundle.js:23,6]

ERROR in boards.ff69073b9694cc46ba12.bundle.js from UglifyJs
Unexpected token: punc ()) [./boards/components/board.js:10,1][boards.ff69073b9694cc46ba12.bundle.js:20,2]

ERROR in filtered_search.f23e55e50cc553121941.bundle.js from UglifyJs
Unexpected token: punc ()) [./filtered_search/dropdown_non_user.js:8,1][filtered_search.f23e55e50cc553121941.bundle.js:17,2]

ERROR in environments_folder.7f64cd62f476cbcd3d9b.bundle.js from UglifyJs
Unexpected token: punc ()) [./environments/components/environment_item.js:34,15][environments_folder.7f64cd62f476cbcd3d9b.bundle.js:52,16]

ERROR in environments.5500347c0cd4ac1b73cf.bundle.js from UglifyJs
Unexpected token: punc ()) [./environments/components/environment_item.js:34,15][environments.5500347c0cd4ac1b73cf.bundle.js:52,16]

ERROR in cycle_analytics.7640abc45edd1a46998f.bundle.js from UglifyJs
Unexpected token: operator (>) [./cycle_analytics/components/stage_code_component.js:5,1][cycle_analytics.7640abc45edd1a46998f.bundle.js:13,9]

ERROR in diff_notes.77276e9aa0cce5df7704.bundle.js from UglifyJs
Unexpected token: punc ()) [./diff_notes/components/new_issue_for_discussion.js:5,1][diff_notes.77276e9aa0cce5df7704.bundle.js:13,2]

ERROR in issue_show.bda99674caccff6f87ae.bundle.js from UglifyJs
Unexpected token: name (Poll) [./lib/utils/poll.js:47,21][issue_show.bda99674caccff6f87ae.bundle.js:1374,6]

ERROR in issuable.1c701cab4b72a83f5786.bundle.js from UglifyJs
Unexpected token: punc ()) [./issuable/time_tracking/components/collapsed_state.js:6,1][issuable.1c701cab4b72a83f5786.bundle.js:23,2]

ERROR in blob.b68f94ec5b143ab6e90b.bundle.js from UglifyJs
Unexpected token: name (EditBlob) [./blob_edit/edit_blob.js:5,21][blob.b68f94ec5b143ab6e90b.bundle.js:12,6]

ERROR in common_vue.2b52c609989508560a41.bundle.js from UglifyJs
Unexpected token punc «(», expected punc «:» [./vue_shared/components/table_pagination.js:47,4][common_vue.2b52c609989508560a41.bundle.js:49,14]

ERROR in merge_conflicts.0db824b95ec4718c496e.bundle.js from UglifyJs
Unexpected token: operator (>) [./merge_conflicts/mixins/line_conflict_actions.js:3,1][merge_conflicts.0db824b95ec4718c496e.bundle.js:8,9]

ERROR in pdf_viewer.29e8b92da113236c10c6.bundle.js from UglifyJs
Unexpected token: punc ()) [./blob/pdf/index.js:10,15][pdf_viewer.29e8b92da113236c10c6.bundle.js:14549,58]

ERROR in notebook_viewer.1130dff7196b565d01ca.bundle.js from UglifyJs
Unexpected token: punc ()) [./blob/notebook/index.js:9,15][notebook_viewer.1130dff7196b565d01ca.bundle.js:7795,58]

ERROR in terminal.2a78825dc07b2337dabb.bundle.js from UglifyJs
Unexpected token: punc ()) [./terminal/terminal_bundle.js:7,2][terminal.2a78825dc07b2337dabb.bundle.js:5663,3]

ERROR in protected_branches.f7036dad4d3a031e5d09.bundle.js from UglifyJs
Unexpected token: operator (>) [./protected_branches/protected_branch_edit.js:4,1][protected_branches.f7036dad4d3a031e5d09.bundle.js:20,9]

ERROR in stl_viewer.949cfff519aaecb10cf4.bundle.js from UglifyJs
Unexpected token: name (Renderer) [./blob/3d_viewer/index.js:9,21][stl_viewer.949cfff519aaecb10cf4.bundle.js:43321,6]

ERROR in network.300bc699ddc3c04e9f1b.bundle.js from UglifyJs
Unexpected token: name (x) [./network/raphael.js:48,6][network.300bc699ddc3c04e9f1b.bundle.js:8826,6]

ERROR in profile.b88df550b560e11c9a08.bundle.js from UglifyJs
Unexpected token: operator (>) [./profile/gl_crop.js:5,1][profile.b88df550b560e11c9a08.bundle.js:22,9]

ERROR in monitoring.405bad94d30699148cb9.bundle.js from UglifyJs
Unexpected token: operator (>) [./monitoring/prometheus_graph.js:16,31][monitoring.405bad94d30699148cb9.bundle.js:44,74]

ERROR in merge_request_widget.2d30d83b38da1d3b3ca8.bundle.js from UglifyJs
Unexpected token: punc ()) [./merge_request_widget/ci_bundle.js:3,1][merge_request_widget.2d30d83b38da1d3b3ca8.bundle.js:8,2]
rake aborted!
Command failed with status (2): [/opt/gitlab/node_modules/.bin/webpack --co...]
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/webpack-rails-0.9.10/lib/tasks/webpack.rake:17:in `block (2 levels) in <top (required)>'
Tasks: TOP => gitlab:assets:compile => webpack:compile
(See full trace by running task with --trace)
 * ERROR: www-apps/gitlab-ce-9.1.4::fritteli failed (config phase):
 *   failed to run rake gitlab:assets:compile
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called pkg_config
 *   environment, line 4277:  Called exec_rake 'gitlab:assets:compile'
 *   environment, line 1853:  Called die
 * The specific snippet of code:
 *              ${command}" || die "failed to run rake $@"
 * 
 * If you need support, post the output of `emerge --info '=www-apps/gitlab-ce-9.1.4::fritteli'`,
 * the complete build log and the output of `emerge -pqv '=www-apps/gitlab-ce-9.1.4::fritteli'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=  CLASSPATH="" JAVA_HOME="/etc/java-config-2/current-system-vm"
JAVACFLAGS="" COMPILER=""
and of course, the output of emerge --info =gitlab-ce-9.1.4
 * The complete build log is located at '/var/tmp/portage/www-apps/gitlab-ce-9.1.4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-apps/gitlab-ce-9.1.4/temp/environment'.
 * Working directory: '/var/tmp/portage/www-apps/gitlab-ce-9.1.4/homedir'
 * S: '/var/tmp/portage/www-apps/gitlab-ce-9.1.4/work/gitlab-ce-9.1.4'
```

**Comment by fritteli** [comment]
Yes, my bad. Please do a fresh sync and try 9.1.4-r1, or 9.2.2.
-------- Ursprüngliche Nachricht --------Von: Dmitriy Zinin <notifications@github.com> Datum: 27.05.17  22:48  (GMT+01:00) An: fritteli/gentoo-overlay <gentoo-overlay@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [fritteli/gentoo-overlay] www-apps/gitlab-ce-9.1.4 upgrade failed (#47) 
[4/4] Building fresh packages...
Done in 22.67s.
 * Cleaning old precompiled assets ...
   /usr/bin/ruby /usr/bin/bundle exec rake gitlab:assets:clean RAILS_ENV=production NODE_ENV=production
I, [2017-05-27T21:04:40.213480 #1872]  INFO -- : Removed application-95970f1eedaa338f70cfe32c114efe83439793bf96581dd001b6d96ce2e04c50.css
 * Cleaning cache ...
   /usr/bin/ruby /usr/bin/bundle exec rake cache:clear RAILS_ENV=production NODE_ENV=production
 * Precompiling assests ...
   /usr/bin/ruby /usr/bin/bundle exec rake gitlab:assets:compile RAILS_ENV=production NODE_ENV=production
warning fsevents@1.0.17: The platform "linux" is incompatible with this module.
/opt/gitlab/node_modules/.bin/webpack --config /opt/gitlab/config/webpack.config.js --bail
Hash: 176d11821dff38b63dec
Version: webpack 2.3.3
Time: 64735ms
[3V7F] ./protected_branches/protected_branches_bundle.js 201 bytes {19} [built]
[3Yvy] ./groups_list.js 591 bytes {0} [built]
[45VA] ./network/network_bundle.js 625 bytes {22} [built]
[80jL] ./commit/pipelines/pipelines_bundle.js 922 bytes {4} [built]
[8z1L] ./commons/index.js 62 bytes {1} [built]
[CtDz] ./blob_edit/blob_bundle.js 1.09 kB {13} [built]
   [1] multi d3 28 bytes {26} [built]
   [2] multi vendor/u2f 28 bytes {25} [built]
[RUZQ] ./profile/profile_bundle.js 43 bytes {23} [built]
[iVFC] ./blob/notebook_viewer.js 104 bytes {17} [built]
[jsyL] ./vue_pipelines_index/index.js 455 bytes {3} [built]
[nYj/] ./blob/stl_viewer.js 569 bytes {21} [built]
[pqyH] ./blob/pdf_viewer.js 89 bytes {16} [built]
[wYwm] ./issue_show/index.js 556 bytes {11} [built]
   [3] multi vue ./vue_shared/common_vue.js 40 bytes {14} [built]
    + 637 hidden modules

ERROR in main.b66fa35e661cc9a3b9bb.bundle.js from UglifyJs
Unexpected token: name (CreateBranchDropdown) [./blob/create_branch_dropdown.js:1,6][main.b66fa35e661cc9a3b9bb.bundle.js:588,6]

ERROR in common.3606a55edd25cb454e34.bundle.js from UglifyJs
Unexpected token operator «=», expected punc «,» [./commons/polyfills/element.js:2,29][common.3606a55edd25cb454e34.bundle.js:7980,100]

ERROR in sketch_viewer.0abacbb479e7c8d0697e.bundle.js from UglifyJs
Unexpected token: punc ()) [./blob/sketch_viewer.js:4,46][sketch_viewer.0abacbb479e7c8d0697e.bundle.js:455,47]

ERROR in vue_pipelines.50c2c7d0d6f03abe40b6.bundle.js from UglifyJs
Unexpected token: name (PipelinesService) [./vue_pipelines_index/services/pipelines_service.js:7,21][vue_pipelines.50c2c7d0d6f03abe40b6.bundle.js:23,6]

ERROR in commit_pipelines.63e6341eb08f12dc6811.bundle.js from UglifyJs
Unexpected token: name (PipelinesService) [./vue_pipelines_index/services/pipelines_service.js:7,21][commit_pipelines.63e6341eb08f12dc6811.bundle.js:23,6]

ERROR in boards.ff69073b9694cc46ba12.bundle.js from UglifyJs
Unexpected token: punc ()) [./boards/components/board.js:10,1][boards.ff69073b9694cc46ba12.bundle.js:20,2]

ERROR in filtered_search.f23e55e50cc553121941.bundle.js from UglifyJs
Unexpected token: punc ()) [./filtered_search/dropdown_non_user.js:8,1][filtered_search.f23e55e50cc553121941.bundle.js:17,2]

ERROR in environments_folder.7f64cd62f476cbcd3d9b.bundle.js from UglifyJs
Unexpected token: punc ()) [./environments/components/environment_item.js:34,15][environments_folder.7f64cd62f476cbcd3d9b.bundle.js:52,16]

ERROR in environments.5500347c0cd4ac1b73cf.bundle.js from UglifyJs
Unexpected token: punc ()) [./environments/components/environment_item.js:34,15][environments.5500347c0cd4ac1b73cf.bundle.js:52,16]

ERROR in cycle_analytics.7640abc45edd1a46998f.bundle.js from UglifyJs
Unexpected token: operator (>) [./cycle_analytics/components/stage_code_component.js:5,1][cycle_analytics.7640abc45edd1a46998f.bundle.js:13,9]

ERROR in diff_notes.77276e9aa0cce5df7704.bundle.js from UglifyJs
Unexpected token: punc ()) [./diff_notes/components/new_issue_for_discussion.js:5,1][diff_notes.77276e9aa0cce5df7704.bundle.js:13,2]

ERROR in issue_show.bda99674caccff6f87ae.bundle.js from UglifyJs
Unexpected token: name (Poll) [./lib/utils/poll.js:47,21][issue_show.bda99674caccff6f87ae.bundle.js:1374,6]

ERROR in issuable.1c701cab4b72a83f5786.bundle.js from UglifyJs
Unexpected token: punc ()) [./issuable/time_tracking/components/collapsed_state.js:6,1][issuable.1c701cab4b72a83f5786.bundle.js:23,2]

ERROR in blob.b68f94ec5b143ab6e90b.bundle.js from UglifyJs
Unexpected token: name (EditBlob) [./blob_edit/edit_blob.js:5,21][blob.b68f94ec5b143ab6e90b.bundle.js:12,6]

ERROR in common_vue.2b52c609989508560a41.bundle.js from UglifyJs
Unexpected token punc «(», expected punc «:» [./vue_shared/components/table_pagination.js:47,4][common_vue.2b52c609989508560a41.bundle.js:49,14]

ERROR in merge_conflicts.0db824b95ec4718c496e.bundle.js from UglifyJs
Unexpected token: operator (>) [./merge_conflicts/mixins/line_conflict_actions.js:3,1][merge_conflicts.0db824b95ec4718c496e.bundle.js:8,9]

ERROR in pdf_viewer.29e8b92da113236c10c6.bundle.js from UglifyJs
Unexpected token: punc ()) [./blob/pdf/index.js:10,15][pdf_viewer.29e8b92da113236c10c6.bundle.js:14549,58]

ERROR in notebook_viewer.1130dff7196b565d01ca.bundle.js from UglifyJs
Unexpected token: punc ()) [./blob/notebook/index.js:9,15][notebook_viewer.1130dff7196b565d01ca.bundle.js:7795,58]

ERROR in terminal.2a78825dc07b2337dabb.bundle.js from UglifyJs
Unexpected token: punc ()) [./terminal/terminal_bundle.js:7,2][terminal.2a78825dc07b2337dabb.bundle.js:5663,3]

ERROR in protected_branches.f7036dad4d3a031e5d09.bundle.js from UglifyJs
Unexpected token: operator (>) [./protected_branches/protected_branch_edit.js:4,1][protected_branches.f7036dad4d3a031e5d09.bundle.js:20,9]

ERROR in stl_viewer.949cfff519aaecb10cf4.bundle.js from UglifyJs
Unexpected token: name (Renderer) [./blob/3d_viewer/index.js:9,21][stl_viewer.949cfff519aaecb10cf4.bundle.js:43321,6]

ERROR in network.300bc699ddc3c04e9f1b.bundle.js from UglifyJs
Unexpected token: name (x) [./network/raphael.js:48,6][network.300bc699ddc3c04e9f1b.bundle.js:8826,6]

ERROR in profile.b88df550b560e11c9a08.bundle.js from UglifyJs
Unexpected token: operator (>) [./profile/gl_crop.js:5,1][profile.b88df550b560e11c9a08.bundle.js:22,9]

ERROR in monitoring.405bad94d30699148cb9.bundle.js from UglifyJs
Unexpected token: operator (>) [./monitoring/prometheus_graph.js:16,31][monitoring.405bad94d30699148cb9.bundle.js:44,74]

ERROR in merge_request_widget.2d30d83b38da1d3b3ca8.bundle.js from UglifyJs
Unexpected token: punc ()) [./merge_request_widget/ci_bundle.js:3,1][merge_request_widget.2d30d83b38da1d3b3ca8.bundle.js:8,2]
rake aborted!
Command failed with status (2): [/opt/gitlab/node_modules/.bin/webpack --co...]
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/webpack-rails-0.9.10/lib/tasks/webpack.rake:17:in `block (2 levels) in <top (required)>'
Tasks: TOP => gitlab:assets:compile => webpack:compile
(See full trace by running task with --trace)
 * ERROR: www-apps/gitlab-ce-9.1.4::fritteli failed (config phase):
 *   failed to run rake gitlab:assets:compile
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called pkg_config
 *   environment, line 4277:  Called exec_rake 'gitlab:assets:compile'
 *   environment, line 1853:  Called die
 * The specific snippet of code:
 *              ${command}" || die "failed to run rake $@"
 * 
 * If you need support, post the output of `emerge --info '=www-apps/gitlab-ce-9.1.4::fritteli'`,
 * the complete build log and the output of `emerge -pqv '=www-apps/gitlab-ce-9.1.4::fritteli'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=  CLASSPATH="" JAVA_HOME="/etc/java-config-2/current-system-vm"
JAVACFLAGS="" COMPILER=""
and of course, the output of emerge --info =gitlab-ce-9.1.4
 * The complete build log is located at '/var/tmp/portage/www-apps/gitlab-ce-9.1.4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-apps/gitlab-ce-9.1.4/temp/environment'.
 * Working directory: '/var/tmp/portage/www-apps/gitlab-ce-9.1.4/homedir'
 * S: '/var/tmp/portage/www-apps/gitlab-ce-9.1.4/work/gitlab-ce-9.1.4'


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fritteli/gentoo-overlay","title":"fritteli/gentoo-overlay","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fritteli/gentoo-overlay"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":" www-apps/gitlab-ce-9.1.4 upgrade failed (#47)"}],"action":{"name":"View Issue","url":"https://github.com/fritteli/gentoo-overlay/issues/47"}}}

**Comment by Kami-no** [comment]
Ok than, thank you.
