### ISSUE TITLE
dev-dotnet/gtk-sharp failed to build

### ISSUE THREAD

**Issue by py-crash** [fritteli/gentoo-overlay#59]
After the official gtk-sharp package was marked for deletion and masked I tried to change to your version. I unmasked the package writing `>=dev-dotnet/gtk-sharp-2.12.45` under `/etc/portage/package.unmask`. However the compilation proccess failed.

You can find attached:
* the [build.log](https://github.com/fritteli/gentoo-overlay/files/6375945/build.log)
* the output of `emerge --info '=dev-dotnet/gtk-sharp-2.12.45::fritteli'`: [emerge-info.txt](https://github.com/fritteli/gentoo-overlay/files/6375946/emerge-info.txt)
* the output of `emerge -pqv '=dev-dotnet/gtk-sharp-2.12.45::fritteli'`: [emerge-pqv.txt](https://github.com/fritteli/gentoo-overlay/files/6375947/emerge-pqv.txt)

Thanks for mantaining this package needed for duplicati.

**Comment by fritteli** [comment]
Sorry for the late reply.
Yeah, the ebuild is in a bad state. I am trying to cobble together an ebuild for version 3 of gtk-sharp.
Perhaps you can use the "dotnet" overlay from https://github.com/gentoo/dotnet instead of mine; they seem to have an ebuild for gtk-sharp 2.12.45, as well as one for version 2.99.3.
I really lack the time to properly maintain this ebuild ... I'm trying my best :)

**Comment by py-crash** [comment]
Hi! Thanks for taking the time. I uninstalled duplicati because of the issues with mono. However, I can do some testing if you update the package.

**Comment by Bigun** [comment]
Yeah, just upgraded all of my boxes to 64-bit VM's, and I'm running into the same issue.  If you need someone else to assist with testing, I am here.

**Comment by fritteli** [comment]
Finally! I've got a working ebuild for gtk-sharp 3.22.2, included in this overlay.
I was able to install this on my ~amd64 machine and I could also install duplicati. While the GUI of duplicati still doesn't work, the still server works.
